# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headslug',
            field=models.SlugField(default='this is a test'),
            preserve_default=False,
        ),
    ]
