# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_headslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headslug',
            field=models.SlugField(unique=True),
        ),
    ]
