# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170604_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headslug',
            field=models.SlugField(default='sdkfhs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'Sports'), (1, 'World-News'), (2, 'India-News'), (3, 'Entertainment and Movies'), (4, 'Uncategorized')], max_length=100),
        ),
    ]
