# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170604_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('0', 'Sports'), ('1', 'World-News'), ('2', 'India-News'), ('3', 'Entertainment and Movies'), ('4', 'Uncategorized')], max_length=100),
        ),
    ]
