# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170604_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('0', 'Sports'), ('1', 'World-News'), ('2', 'India-News'), ('3', 'Entertainment and Movies'), ('4', 'Uncategorized')], default='4', max_length=100),
        ),
    ]
