# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170605_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='this is summarized text'),
            preserve_default=False,
        ),
    ]
