# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170605_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('0', 'Sports'), ('2', 'World-News'), ('1', 'India-News'), ('4', 'Entertainment and Movies'), ('5', 'Uncategorized'), ('3', 'Science and Technology')], default='4', max_length=100),
        ),
    ]
