# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170608_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=200)),
                ('emotion', models.CharField(choices=[('-1', 'Negative'), ('0', 'Neutral'), ('1', 'Positive')], max_length=50)),
                ('relavent', models.IntegerField()),
                ('posttweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
            ],
        ),
    ]
