# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=400),
        ),
    ]
