# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170609_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='relavent',
            field=models.FloatField(),
        ),
    ]
